[workspace]
members = ["client", "protocol", "server", "server_lib"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
avian3d = "0.4"
axum = "0.7"
bevy = { version = "0.17.2", default-features = false }
bevy_async_task = "0.9"
bevy_egui = "0.38"
bevy_embedded_assets = "0.14"
bevy-inspector-egui = "0.35.0"
# bevy_mod_picking = "0.20" # Removed: upstreamed to Bevy since 0.15
# bevy_mod_raycast = "0.18" # Removed: upstreamed to Bevy since 0.15
bevy_mod_reqwest = "0.20"
bevy_transform = { version = "*", features = ["serialize"] }
bytemuck = "1"
clap = { version = "4.5.18", features = ["derive"] }
crossbeam-channel = "0.5.13"
data-encoding = "2.6"
doc_consts = "0.2"
egui-aesthetix = { git = "https://github.com/thebashpotato/egui-aesthetix", branch = "dependabot/cargo/egui-0.33", features = ["nord"] }
egui_dock = "0.18"
egui-notify = "0.21.0"
egui-phosphor = { git = "https://github.com/philpax/egui-phosphor" }
egui_plot = "0.33"
futures-intrusive = "0.5.0"
getrandom = { version = "0.2", features = ["js"] }
git-version = "0.3"
image = { version = "0.25.2", default-features = false, features = [
    "png",
    "exr",
] }
# bodge: force vendored TLS to get around OpenSSL cross-compilation issues
native-tls = { version = "0.2", features = ["vendored"] }
paste = "1.0"
rand = "0.8.5"
reqwest = "0.12.7"
rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1"
toml = "0.8"
tower-http = { version = "0.5", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = "0.3"
transform-gizmo-bevy = { git = "https://github.com/pindash-io/transform-gizmo.git", branch = "bevy-0.17" }
wasm-bindgen-futures = "0.4"
web-time = "1.1.0"
wgpu = "26.0"
zip = { version = "2.2", default-features = false, features = ["deflate"] }

[profile.dev]
# Enable a small amount of optimization in the dev profile.
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
