[package]
name = "prismata_server_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
data-encoding = { workspace = true }
git-version = { workspace = true }
image = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

prismata_protocol = { path = "../protocol" }

rucomfyui = { git = "https://github.com/philpax/rucomfyui.git", default-features = false, features = ["rustls-tls", "typed_nodes"] }
# rucomfyui = { path = "../../rucomfyui" }
